# window
TMUX_THEME_WINDOW_FG = 'default'
TMUX_THEME_WINDOW_BG = 'default'
TMUX_THEME_WINDOWS_STATUS_FORMAT_FG = 'default'
TMUX_THEME_WINDOWS_STATUS_FORMAT_BG = '#96cdcd'

# pane
TMUX_THEME_FOCUSED_PANE_FG = 'default'
TMUX_THEME_FOCUSED_PANE_BG = 'default'
TMUX_THEME_PANE_BORDER_STYLE = 'thin'
TMUX_THEME_PANE_BORDER = '#444444'
TMUX_THEME_PANE_ACTIVE_BORDER_STYLE = '#00afff'

# status line
TMUX_THEME_MESSAGE_COMMAND_STYLE_FG = 'default'
TMUX_THEME_MESSAGE_COMMAND_STYLE_BG = 'default'

TMUX_THEME_MESSAGE_STYLE_FG = '#ffff00'
TMUX_THEME_MESSAGE_STYLE_BG = '#000000'

TMUX_THEME_STATUS_STYLE_FG = 'default'
TMUX_THEME_STATUS_STYLE_BG = '#696969'

TMUX_THEME_STATUS_LEFT_STYLE_FG = 'default'
TMUX_THEME_STATUS_LEFT_STYLE_BG = 'default'
TMUX_THEME_STATUS_LEFT_LENGTH = 100

TMUX_THEME_STATUS_RIGHT_STYLE_FG = 'default'
TMUX_THEME_STATUS_RIGHT_STYLE_BG = 'default'
TMUX_THEME_STATUS_RIGHT_LENGTH = 100

TMUX_THEME_SEPARATOR_COLOR = '#ffff00'

TMUX_STATUS_INTERVAL = 1
